name: AutoShutdown
main: net.stupendous.autoshutdown.AutoShutdownPlugin
version: 2.7.1
api-version: 1.13
commands:
  autoshutdown:
    description: Interact with the AutoShutdown plugin
    usage: "Usage: '/autoshutdown help'"
  as:
    description: Interact with the AutoShutdown plugin
    usage: "Usage: '/as help'"
    